import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

// Copy calendar-bridge binary if it exists
const copyBinary = () => {
  const binaryPath = path.join(process.cwd(), "calendar-bridge");
  if (fs.existsSync(binaryPath)) {
    // Binary is already in the root, which is where it should be for the plugin
    // Make sure it's executable
    try {
      fs.chmodSync(binaryPath, 0o755);
    } catch (e) {
      console.warn("Could not set binary permissions:", e);
    }
  } else {
    console.warn("calendar-bridge binary not found. Run 'bun run build:swift' first.");
  }
};

if (prod) {
  await context.rebuild();
  copyBinary();
  process.exit(0);
} else {
  await context.watch();
  copyBinary();
}
